[book]
authors = ["the pace authors"]
description = "pace - Mindful Time Tracking: Simplify Your Focus and Boost Productivity Effortlessly."
language = "en"
multilingual = false
src = "src"
title = "pace dev documentation"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
curly-quotes = true
default-theme = "ayu"
site-url = "/dev-docs/"
git-repository-url = "https://github.com/pace-rs/dev-docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/pace-rs/dev-docs/edit/main/{path}"
cname = "pace.cli.rs"
additional-css = ["./styles/last-changed.css"]

[output.html.fold]
enable = true
level = 1

[output.pandoc]
optional = true
hosted-html = "https://pace.cli.rs/dev-docs/"

[output.pandoc.profile.pdf]
output-file = "pace-dev-docs.pdf"
pdf-engine = "lualatex"

[output.pandoc.profile.pdf.variables]
mainfont = "Noto Serif"
sansfont = "Noto Sans"
monofont = "Noto Sans Mono"
mainfontfallback = ["NotoSerifCJKSC:"]
geometry = ["margin=1.25in"]
linkcolor = "blue"
urlcolor = "red"
